version = "3.8.3"
runner.dialect = scala213
maxColumn = 120
indent.main = 2
align.preset = some
align.openParenCtrlSite = false
newlines.topLevelStatementBlankLines = [
  { blanks = 1 }
]
rewrite.rules = [SortImports]
fileOverride {
  "glob:**/out/mill-build/generatedScriptSources.dest/support/**" {
     runner.dialect = scala3
  }
  "glob:**/build.mill/**" {
     runner.dialect = scala3
  }
}
