package nzea_rtl

import chisel3._
import chisel3.experimental.ExtModule

/** Write/read ports for one annotated register inside a [[StatsRegs]] black box. */
class StatsRegPort(val en: Bool, val data: UInt, val value: UInt)

/**
 * Simulation-only container of `/*verilator public_flat_rd*/`-annotated registers.
 *
 * The registers are declared in SystemVerilog generated by [[StatsRegs.verilog]]
 * and inlined via `setInline`. firtool writes that text verbatim as
 * `<moduleName>.sv` next to the generated RTL, so the metacomments reach
 * Verilator unchanged: every register becomes VPI-readable by its leaf name
 * (contract: `stat_*` leaf names are globally unique). Other tools (iverilog,
 * Vivado) treat the metacomment as an ordinary comment.
 *
 * State lives inside the black box; all update logic stays on the Chisel side
 * through per-register `en`/`data` write ports plus a `value` read-back port.
 * The black box is opaque to firtool, so it is never constant-folded or
 * removed — no `dontTouch` needed. Instantiate it only when simulation is
 * enabled (e.g. under `config.sim`) so synthesis sees zero resources.
 */
class StatsRegs(moduleName: String, regs: Seq[(String, Int)]) extends ExtModule {
  override def desiredName: String = moduleName

  val clock = IO(Input(Clock()))
  val reset = IO(Input(Bool()))

  /** Per-register ports, keyed by register name. */
  val ports: Map[String, StatsRegPort] = regs.map { case (name, width) =>
    name -> new StatsRegPort(
      en    = IO(Input(Bool())).suggestName(s"${name}_en"),
      data  = IO(Input(UInt(width.W))).suggestName(s"${name}_data"),
      value = IO(Output(UInt(width.W))).suggestName(s"${name}_value")
    )
  }.toMap

  setInline(s"$moduleName.sv", StatsRegs.verilog(moduleName, regs))
}

object StatsRegs {

  /** Generate the SystemVerilog body for [[StatsRegs]]. Pure function for tests. */
  private[nzea_rtl] def verilog(moduleName: String, regs: Seq[(String, Int)]): String = {
    val portsDecl = regs.map { case (name, width) =>
      s"  input ${name}_en,\n  input [${width - 1}:0] ${name}_data,\n  output [${width - 1}:0] ${name}_value"
    }
    val regsDecl = regs.map { case (name, width) =>
      s"  reg [${width - 1}:0] $name /*verilator public_flat_rd*/;\n  assign ${name}_value = $name;"
    }
    val resets = regs.map { case (name, _) => s"      $name <= '0;" }
    val writes = regs.map { case (name, _) => s"      if (${name}_en) $name <= ${name}_data;" }
    s"""module $moduleName(
       |  input clock,
       |  input reset,
       |${portsDecl.mkString(",\n")}
       |);
       |${regsDecl.mkString("\n")}
       |  always @(posedge clock) begin
       |    if (reset) begin
       |${resets.mkString("\n")}
       |    end else begin
       |${writes.mkString("\n")}
       |    end
       |  end
       |endmodule
       |""".stripMargin
  }
}
