[package]
name = "pulse_cli"
version = "0.1.0"
edition = "2024"
license = "MIT"
authors = [ "wenjiu <27843087979@qq.com>" ]

[dependencies]
pulse_wave = { path = "../pulse_wave" }
tracing.workspace = true
anyhow.workspace = true

clap = { workspace = true, features = [ "derive", "color", "env" ] }

[lints]
workspace = true
